### ISSUE TITLE
Menus and Dialog Boxes Do Not Show

### ISSUE THREAD

**Issue by dpassey-splunk** [adityapant1286/Raven#1]
On IntelliJ IDEA Ultimate 2023.3.6->Build #IU-233.15026.9, built on March 20, 2024 using the Raven theme dropdowns, menus, and dialog boxes do not show up (invisible).

For example, the "Find Everywhere" dialog box does not show up when invoked using the mac command Shift + Cmd + F

**Comment by adityapant1286** [comment]
@dpassey-splunk Thank you for reporting. It is working on windows. However, I will have a look on Mac.

## Windows
### Dropdown
![image](https://github.com/adityapant1286/Raven/assets/13958935/3e86d274-783f-4401-94fa-83c47ec89231)

### Find Everywhere
![image](https://github.com/adityapant1286/Raven/assets/13958935/c340d926-eced-4443-92f0-6cf92a44edae)

**Comment by adityapant1286** [comment]
@dpassey-splunk sorry for the delay. I do not have Macbook, so it took some time to reproduce. A friend of mine helped me. 
We noticed the dropdown is not clickable and search everywhere didn't open. So it appears, on MacOS most of the overlay/pop up elements are affected. I will dig further and work on the issue.

**Comment by adityapant1286** [comment]
@dpassey-splunk I have fixed the issue on MacOS. It will be available in update version 1.0.3 (48 hours approx).
Closing this for now. Let me know if the issue persist.
